services:
    tibber-watcher:
        image: ghcr.io/kvasbo/tibber-watcher:main
        restart: unless-stopped
        stdin_open: true
        tty: true
        environment:
            - TIBBER_KEY=${TIBBER_KEY}
            - TIBBER_ID_HOME=${TIBBER_ID_HOME}
            - TIBBER_ID_CABIN=${TIBBER_ID_CABIN}
            - MQTT_URL=${MQTT_URL}
            - MQTT_PORT=${MQTT_PORT}
            - MQTT_USER=${MQTT_USER}
            - MQTT_PASS=${MQTT_PASS}
            - MQTT_ROOT_TOPIC=${MQTT_ROOT_TOPIC}
networks:
    default:
        name: ${NETWORK_NAME}
        external: true
